# Generated by Django 3.0.4 on 2020-04-14 22:12

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.poster_path, verbose_name='Poster'),
        ),
    ]
